sudo: required
dist: xenial

language: java

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2
  - $HOME/.p2

before_cache:
  # remove resolver-status.properties, they change with each run and invalidate the cache
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
  
before_install:
  - echo "MAVEN_OPTS='-Xms1g -Xmx2g -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN'" > ~/.mavenrc
install:
  - |
    function extra_maven_opts() {
        if [ "$TRAVIS_JDK_VERSION" != "openjdk8" ]; then echo "-Denforcer.skip=true"; fi;
    }
    function prevent_timeout() {
        local i=0
        while [ -e /proc/$1 ]; do
            # print zero width char every 3 minutes while building
            if [ "$i" -eq "180" ]; then printf %b '\u200b'; i=0; else i=$((i+1)); fi
            sleep 1
        done
    }
    function mvnp() {
        set -o pipefail # exit build with error when pipes fail
        local command=(mvn $@)
        exec "${command[@]}" 2>&1
        local pid=$!
        prevent_timeout $pid &
        wait $pid
    }
env: # required for allowing failures
matrix:
  allow_failures:
    - jdk: openjdk11
script:
  - echo "Changed files:"
  - git diff --name-only HEAD...$TRAVIS_BRANCH
  - mvnp clean install -B -DskipChecks=true -DskipTests=true $(extra_maven_opts)
